<?php

# Errors
const SOMETHING_WENT_WRONG = 'Something went wrong.';

# HTTP Status codes - DO NOT REMOVE
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
const HTTP_STATUS_BAD_REQUEST = 400;
const HTTP_STATUS_NOT_FOUND = 404;
const HTTP_STATUS_NOT_MODIFIED = 304;
